net.Receive("NMCP::NOTIFICATIONS", function(len,ply)
	local string = net.ReadString()
	local type = net.ReadInt()
	local sound = net.ReadString()
	local time = net.ReadInt()
    print(ply)
    notification.AddLegacy( string, type, time )
    surface.PlaySound( sound )
    Msg( string .. "\n" )
end)